export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const FETCH_ALL_CUSTOMER = 'FETCH_ALL_CUSTOMER';
export const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH';
export const FETCH_CUSTOMER = 'FETCH_CUSTOMER';
export const LIKE = 'LIKE';
export const COMMENT = 'COMMENT';
export const END_LOADING = 'END_LOADING';
export const START_LOADING = 'START_LOADING';
export const FETCH_BY_CONSULTANT = 'FETCH_BY_CONSULTANT';
export const FETCH_BY_CLIENT = 'FETCH_BY_CLIENT';

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

export const FETCH_ALL_PROGRAM = 'FETCH_ALL_PROGRAM';
export const FETCH_PROGRAM_BY_CLIENT = 'FETCH_PROGRAM_BY_CLIENT';
export const CREATE_PROGRAM = 'CREATE_PROGRAM';
export const UPDATE_PROGRAM = 'UPDATE_PROGRAM';
export const DELETE_PROGRAM = 'DELETE_PROGRAM';
export const FETCH_PROGRAM = 'FETCH_PROGRAM';


export const FETCH_ALL_FOLDERS = 'FETCH_ALL_FOLDERS';
export const FETCH_FOLDERS_ERROR = 'FETCH_FOLDERS_ERROR';

export const FETCH_FOLDER = 'FETCH_FOLDER';
export const CREATE_FOLDER = 'CREATE_FOLDER';
export const UPDATE_FOLDER = 'UPDATE_FOLDER';
export const DELETE_FOLDER = 'DELETE_FOLDER';
export const FETCH_BY_CLIENT_FOLDER = 'FETCH_BY_CLIENT_FOLDER';
export const FETCH_BY_CONSULTANT_FOLDER = 'FETCH_BY_CONSULTANT_FOLDER';
export const FETCH_FOLDER_BY_SEARCH = 'FETCH_FOLDER_BY_SEARCH';
export const FETCH_FOLDER_BY_PROGRAM = 'FETCH_FOLDER_BY_PROGRAM';

export const REQUEST_PAGE = 'REQUEST_PAGE';
export const RECEIVE_PAGE = 'RECEIVE_PAGE';
export const INVALIDATE_PAGE = 'INVALIDATE_PAGE';


export const FETCH_OTHERS = 'FETCH_OTHERS';
export const FETCH_OTHERS_BY_CUSTOMER = 'FETCH_OTHERS_BY_CUSTOMER';
export const INSERT_OTHERS = 'INSERT_OTHERS';





